imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

doctrine:
    dbal:
        connections:
            default:
                logging: true
                dbname: sofachamps_test
                user: sofachamps_test
                password: sofachamps_test

security:
    firewalls:
        main:
            http_basic: ~

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

liip_functional_test: ~
