sofa_champs_super_bowl_challenge:
    resource: "@SofaChampsSuperBowlChallengeBundle/Controller/"
    type:     annotation
    prefix:   /superbowl-challenge

sofa_champs_nfl_admin:
    resource: "@SofaChampsNFLBundle/Controller/"
    type:     annotation
    prefix:   /nfl_admin

college_crazies_user:
    resource: "@CollegeCraziesUserBundle/Controller/"
    type:     annotation
    prefix:   /

CollegeCraziesMainBundle:
    resource: "@CollegeCraziesMainBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
