services:
    listener.picks_locked:
        class: CollegeCrazies\Bundle\MainBundle\Listener\PicksLockedListener
        arguments:
            - @picks_locked_manager
            - @session
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
