services:
    team.controller:
        scope: prototype
        class: CollegeCrazies\Bundle\MainBundle\Controller\TeamController

    game.controller:
        scope: prototype
        class: CollegeCrazies\Bundle\MainBundle\Controller\GameController

    college_crazies.user.manager:
        class: CollegeCrazies\Bundle\MainBundle\Entity\MyUserManager
        public: false
        parent: fos_user.user_manager.default

    user.sorter:
        class: CollegeCrazies\Bundle\MainBundle\Service\UserSorter

    transformer.team:
        class: CollegeCrazies\Bundle\MainBundle\Form\DataTransformer\TeamTransformer
        arguments: ["@doctrine.orm.entity_manager"]

    transformer.game:
        class: CollegeCrazies\Bundle\MainBundle\Form\DataTransformer\GameTransformer
        arguments: ["@doctrine.orm.entity_manager"]

    form.type.hidden_team:
        class: CollegeCrazies\Bundle\MainBundle\Form\Type\HiddenTeamType
        arguments: ["@transformer.team"]
        tags:
            - { name: form.type, alias: hidden_team }

    form.type.hidden_game:
        class: CollegeCrazies\Bundle\MainBundle\Form\Type\HiddenGameType
        arguments: ["@transformer.game"]
        tags:
            - { name: form.type, alias: hidden_game }
