services:
    team.controller:
        scope: prototype
        class: CollegeCrazies\Bundle\MainBundle\Controller\TeamController

    game.controller:
        scope: prototype
        class: CollegeCrazies\Bundle\MainBundle\Controller\GameController
