services:
    sofachamps.admin.core.user:
        class: SofaChamps\Bundle\CoreBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Core", label: "Users" }
        arguments:
            - ~
            - SofaChamps\Bundle\CoreBundle\Entity\User
            - 'SonataAdminBundle:CRUD'
        calls:
            - ["setTemplate", ["list", "SofaChampsCoreBundle:Admin:User\list.html.twig"]]
