services:
    sofachamps.user.manager:
        class: SofaChamps\Bundle\CoreBundle\Entity\MyUserManager
        public: false
        parent: fos_user.user_manager.default

    config.curdate:
        class: DateTime
        factory_class: \DateTime

    config.curyear:
        class: string
        factory_service: config.curdate
        factory_method: format
        arguments:
            - Y
