services:
    sofachamps.admin.bp.game:
        class: SofaChamps\Bundle\BowlPickemBundle\Admin\GameAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Bowl Pickem", label: "Games" }
        arguments:
            - ~
            - SofaChamps\Bundle\BowlPickemBundle\Entity\Game
            - 'SonataAdminBundle:CRUD'

    sofachamps.admin.bp.league:
        class: SofaChamps\Bundle\BowlPickemBundle\Admin\LeagueAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Bowl Pickem", label: "Leagues" }
        arguments:
            - ~
            - SofaChamps\Bundle\BowlPickemBundle\Entity\League
            - 'SonataAdminBundle:CRUD'

    sofachamps.admin.bp.team:
        class: SofaChamps\Bundle\BowlPickemBundle\Admin\TeamAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Bowl Pickem", label: "Teams" }
        arguments:
            - ~
            - SofaChamps\Bundle\BowlPickemBundle\Entity\Team
            - 'SonataAdminBundle:CRUD'
