services:
    sofachamps.bowlpickem.listener.password_resetting:
        class: SofaChamps\Bundle\BowlPickemBundle\EventListener\PasswordResettingListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }

    sofachamps.bowlpickem.listener.registration:
        class: SofaChamps\Bundle\BowlPickemBundle\EventListener\RegistrationListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }
