services:
    college_crazies.registration.form.type:
        class: CollegeCrazies\Bundle\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: college_crazies_user_registration }

    college_crazies.profile.form.type:
        class: CollegeCrazies\Bundle\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: college_crazies_user_profile }

    college_crazies.listener.password_resetting:
        class: CollegeCrazies\Bundle\UserBundle\EventListener\PasswordResettingListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }

    college_crazies.listener.registration:
        class: CollegeCrazies\Bundle\UserBundle\EventListener\RegistrationListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }
